apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: your_root_password  # Ubah dengan password root MySQL yang aman
        - name: MYSQL_DATABASE
          value: your_database_name  # Nama database yang akan dibuat
        - name: MYSQL_USER
          value: your_user          # Nama user MySQL
        - name: MYSQL_PASSWORD
          value: your_password      # Password untuk user tersebut
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
